services:
  mongodb:
    image: bitnami/mongodb:latest
    hostname: apptrackrmongo
    volumes:
      - ./db/data:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=user
    ports:
      - 27017:27017
  mongodb-ui:
      image: mongo-express:latest
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=apptrackrmongo
      ports:
      - 8081:8081