services:
  apptrackr:
    build: .
    environment:
      - ANTHROPIC_API_KEY
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/creds.json
    ports:
      - 8501:8501