services:
  mongodb:
    image: mongo:latest
    hostname: apptrackrmongo
    volumes:
      - ./db/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  mongodb-ui:
    image: mongo-express:latest
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_SERVER=apptrackrmongo
    ports:
    - 8081:8081
    depends_on:
      - mongodb